let sessionList = [{
  color: '-accent1',
  title: 'ADVANCED SOFTWARE ENGINEERING',
  attr: 'ASE',
  code: 'CS7CS3',
  start: '15:00',
  end: '16:00',
  lecturer: 'PROF. SIOBHAN CLARKE',
  type: 'LECTURE',
  location: 'LB04 - SL LECTURE THEATRE (COMPUTER SCIENCE 1ST CALL)(A) [Lloyd Institute(INS Building)]',
  locationUrl: 'https://goo.gl/maps/rbh9a134oCrb4UCj9',
  building: 'INS Building',
  column: 'monday',
  row: 'time-1500 / time-1600'
}, {
  color: '-accent7',
  title: 'DATA ANALYTICS',
  attr: 'DA',
  code: 'CS7DS1',
  start: '15:00',
  end: '16:00',
  lecturer: 'DR. BAHMAN HONAR',
  type: 'LECTURE',
  location: 'LB08-SL LECTURE THEATRE(COMPUTER SCI ENCE 1ST CALL)(A)[Lloyd Institute (INS Building)]',
  locationUrl: 'https://goo.gl/maps/rbh9a134oCrb4UCj9',
  building: 'Lloyd Institute (INS Building)',
  column: 'monday',
  row: 'time-1700 / time-1800'
}, {
  color: '-accent2',
  title: 'COMPUTER GRAPHICS',
  attr: 'CG',
  code: 'CS7GV6',
  start: '12:00',
  end: '13:00',
  lecturer: 'MS. RACHEL MC DONNELL',
  type: 'LECTURE',
  location: ':1.20 - INS STATISTICS 1.20 (SCSS ONLY) [Lloyd Institute (INS Building)]',
  locationUrl: 'https://goo.gl/maps/rbh9a134oCrb4UCj9',
  building: 'INS Building',
  column: 'tuesday',
  row: 'time-1200 / time-1300'
}, {
  color: '-accent2',
  title: 'COMPUTER GRAPHICS',
  attr: 'CG',
  code: 'CS7GV6',
  start: '13:00',
  end: '14:00',
  lecturer: 'MS. RACHEL MC DONNELL',
  type: 'LECTURE',
  location: ':1.20 - INS STATISTICS 1.20 (SCSS ONLY) [Lloyd Institute (INS Building)] \n' +
    'LG37 - PC LAB COMP SC ONLY (P) [O\'Reilly Institute]',
  locationUrl: 'https://goo.gl/maps/rbh9a134oCrb4UCj9',
  building: 'INS Building',
  column: 'tuesday',
  row: 'time-1300 / time-1400'
}, {
  color: '-accent3',
  title: 'MACHINE LEARNING',
  attr: 'ML',
  code: 'CS7CS4',
  start: '17:00',
  end: '18:00',
  lecturer: 'PROF. DOUGLAS LEITH, DR. GIOVANNI DI LIBERTO',
  type: 'LECTURE',
  location: 'DOLT0.32 - SL LECTURE THEATRE LOWER (NURSING 1ST CALL) (A) [School of Nursing and Midwifery]',
  locationUrl: 'https://goo.gl/maps/AkXg8MVpGp7KnVcE6',
  building: 'School of Nursing',
  column: 'tuesday',
  row: 'time-1700 / time-1800'
}, {
  color: '-accent4',
  title: 'COMPUTER VISION',
  attr: 'CV',
  code: 'CS7GV1',
  start: '9:00',
  end: '10:00',
  lecturer: 'MISS CAROL ANN OSULLIVAN',
  type: 'LECTURE',
  location: '1.07 - INS STATISTICS 1.07 (SCSS ONLY) [Lloyd Institute (INS Building)]',
  locationUrl: 'https://goo.gl/maps/rbh9a134oCrb4UCj9',
  building: 'INS Building',
  column: 'wednesday',
  row: 'time-0900 / time-1000'
}, {
  color: '-accent4',
  title: 'COMPUTER VISION',
  attr: 'CV',
  code: 'CS7GV1',
  start: '10:00',
  end: '11:00',
  lecturer: 'MISS CAROL ANN OSULLIVAN',
  type: 'LECTURE',
  location: ':LG37 - PC LAB COMP SC ONLY (P) [O\'Reilly Institute]',
  locationUrl: 'https://goo.gl/maps/X2iXK3TQLJK92xrP6',
  building: 'O\'Reilly Institute',
  column: 'wednesday',
  row: 'time-1000 / time-1100'
}, {
  color: '-accent5',
  title: 'RESEARCH AND INNOVATION METHODS',
  attr: 'RIM',
  code: 'CS7CS6',
  start: '14:00',
  end: '16:00',
  lecturer: 'DR. DAVID LEWIS, MS. GAYE MARY STEPHENS',
  type: 'LECTURE',
  location: 'MACNEIL3 - SL MACNEILL LECTURE THEATRE 3 (A) [Hamilton Building]',
  locationUrl: 'https://goo.gl/maps/zVTKdVYsjKtrFJeh9',
  building: 'Hamilton Building',
  column: 'wednesday',
  row: 'time-1400 / time-1600'
}, {
  color: '-accent7',
  title: 'DATA ANALYTICS',
  attr: 'DA',
  code: 'CS7DS1',
  start: '15:00',
  end: '16:00',
  lecturer: 'DR. BAHMAN HONAR',
  type: 'LECTURE',
  location: '1.07 - INS STATISTICS 1.07 (SCSS ONLY) [Lloyd Institute (INS Building)]',
  locationUrl: 'https://goo.gl/maps/rbh9a134oCrb4UCj9',
  building: 'INS Building',
  column: 'thursday',
  row: 'time-1700 / time-1800'
}, {
  color: '-accent1',
  title: 'ADVANCED SOFTWARE ENGINEERING',
  attr: 'ASE',
  code: 'CS7CS3',
  start: '9:00',
  end: '11:00',
  lecturer: 'PROF. SIOBHAN CLARKE',
  type: 'LECTURE',
  location: 'LB01 - LB01 COMPUTER SCIENCE ONLY (B) [Lloyd Institute (INS Building)]',
  locationUrl: 'https://goo.gl/maps/rbh9a134oCrb4UCj9',
  building: 'INS Building',
  column: 'friday',
  row: 'time-0900 / time-1100'
}, {
  color: '-accent3',
  title: 'MACHINE LEARNING',
  attr: 'ML',
  code: 'CS7CS4',
  start: '11:00',
  end: '12:00',
  lecturer: 'DR. GIOVANNI DI LIBERTO',
  type: 'LECTURE',
  location: 'JOYL4 - SL JOYL LECTURE THEATRE 4(A) [Hamilton Building]',
  locationUrl: 'https://goo.gl/maps/zVTKdVYsjKtrFJeh9',
  building: 'Hamilton Building',
  column: 'friday',
  row: 'time-1100 / time-1200'
},  {
  color: '-accent6',
  title: 'MATHEMATICS OF LIGHT AND SOUND',
  attr: 'MLS',
  code: 'CS7GV2',
  start: '13:00',
  end: '15:00',
  lecturer: 'DR. FERGAL SHEVLIN',
  type: 'LECTURE',
  location: '4.09 - SCSS (ONLY) [7-9 Sth Leinster Street (Phoenix House)]',
  locationUrl: 'https://goo.gl/maps/tUWYfVNa3mhP7bCo9',
  building: 'Phoenix House',
  column: 'friday',
  row: 'time-1300 / time-1500'
}]
